export const API_BASE_URL = 'http://localhost:3000';
export const GET_EMPLOYEE_LIST = 'GET_EMPLOYEE_LIST';
export const GET_OPENING_LIST = 'GET_OPENING_LIST';
export const GET_REFERRAL_LIST = 'GET_REFERRAL_LIST';
export const GET_MY_REFERRAL_LIST = 'GET_MY_REFERRAL_LIST';
export const GET_APPLICATION_LIST = 'GET_APPLICATION_LIST';
